Проверка объекта на наличие свойств
js-tasks-ru/jsbasic-20200727_sword-and-brush pull request #5
Opened 2020-08-02 19:38 UTC by Red-Warrior

2020-08-02 19:45 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Определите, пуст ли объект
+ {} должен вернуть true
+ объект со свойством undefined должен считаться не пустым
+ объект с удалённым свойством - пустой
+ если у объекта есть хоть одно свойство, то он не пустой
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-08-02 20:37 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-02 22:02 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-03 07:49 UTC, dolgachio requested changes
Ваше решение уже правильное и корректное, в тоже время, код можно немного улучшить.
Посмотрите, пожалуйста, на мои комментарии =)

2020-08-03 07:49 UTC, stas-dolgachov commented on 2-module/2-task/index.js
> +  let check = (Object.keys(obj).length === 0) ? true : false;
Скажите, а если мы полностью уберем тернарный оператор и просто вернет сравнение, пройдет ли такое решение проверку?
`return Object.keys(obj).length === 0;`

2020-08-03 07:49 UTC, stas-dolgachov commented on 2-module/1-task/index.js
> +  let result = Object.values(data).filter(item => typeof item === "number").reduce((a, b) => a + b, 0);
Хорошее решение. 

В тоже время, меня немного смущает именование переменных. 
Попробуйте придумать какие-то смысловые названия для переменных `a` и `b`.

2020-08-03 07:49 UTC, stas-dolgachov commented on 2-module/3-task/index.js
> +  read(a, b) {
Отлично!

2020-08-03 07:49 UTC, stas-dolgachov commented on 2-module/1-task/index.js
> +  let result = Object.values(data).filter(item => typeof item === "number").reduce((a, b) => a + b, 0);
Здорово, что вы здесь использовали вызов методов по цепочке!

2020-08-07 12:27 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-07 12:37 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-07 12:49 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-07 15:19 UTC, dolgachio approved these changes

2020-08-07 15:19 UTC, merged